### ISSUE TITLE
More efficient data structure

### ISSUE THREAD

**Issue by TheTomster** [TheTomster/lwe#10]
Currently llwe stores text in a flat buffer, and moves large pieces of text in memory whenever a character is inserted.  It should use a more efficient data structure.  I'm thinking a gap buffer is the best combination of simplicity and speed, but maybe a tree structure or piece table could be used if it is simple enough.

**Comment by TheTomster** [comment]
While I haven't noticed any issues with the large flat buffer for normal typing and editing operations within `llwe`, I did find a case where the naive buffer storage causes noticeable slowness.  I pasted a large string using `tmux`'s paste function, and it took time to insert each individual character.  I believe that for normal typing we're adding things fast enough to avoid noticeable delays, but when many characters are added automatically the individual additions add up to a big delay.

A gap buffer would handle this more gracefully since a large `tmux` paste would add characters into the gap which should be more responsive than resizing the entire buffer each character.

**Comment by TheTomster** [comment]
Actually this is quite noticeable in regular typing.  Going to have to prioritize this.

**Comment by atrivedi** [comment]
I actually do want to give this a try. how do you feel about 

https://github.com/josephg/librope

**Comment by TheTomster** [comment]
If we're gonna use a library, that one looks good.  I'm also a big fan of the idea of making our own gap buffer or rope solution so that we don't have to depend on anything besides curses.

I like this library though since it looks like we could just drop in rope.c and rope.h, include their license, and be good to go.  So I say go for it!

**Comment by TheTomster** [comment]
Turns out the noticeable lag in regular typing was due to the slowness in refresh bounds.  So this isn't a huge emergency any more.  Things are nice and quick even on the pi.  I imagine very large files are the only case where this will be an issue.

**Comment by TheTomster** [comment]
Closing for now given that the basic approach is working well even on raspberry pi.
