### ISSUE TITLE
Building on OS X

### ISSUE THREAD

**Issue by tjbell** [TheTomster/lwe#57]
Will this build on OS X?
Right now I'm receiving 

undo.c:50:9: error: implicit declaration of function 'reallocarray' is invalid
      in C99 [-Werror,-Wimplicit-function-declaration]

```
            new = reallocarray(*l, *a, sizeof(**l));
```

Among other errors.

**Comment by TheTomster** [comment]
Ah, I used some non-portable BSD things.  I'll work on a patch with portable replacements so that it can build on OS X.

**Comment by TheTomster** [comment]
I've pushed some changes that should make everything compile happily on OS X. I tested on a friend's Macbook and was able to compile with just one warning.

**Comment by tjbell** [comment]
Compiles happily in all my testing as well.
